apiVersion: 0.0.1-SNAPSHOT
kind: Deployment
metadata:
  name: spmodule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spmodule
  template:
    metadata:
      labels:
        app: spmodule
    spec:
      containers:
        - name: myimage1
          image: gcr.io/ornate-lead-338319/myimage1:v2
          ports: 
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spmoduleservice
spec:
  type: LoadBalancer
  selector:
    app: sp